# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7357561a9bd8912a9074c2dfde7126cc8476509407e7f0d57e3354e9d926cf935255596c08a9d2d1817b711ff6f79713a4d2ff895faad8f9790cba60049317e5

test:
  secret_key_base: 8da1e0fc02af7e873554935c81bf4b894f11940577d80f948cd9f13d9fdefd0ba363e62d6eb5180a6d2a818adf1c7c9227e409dd306ba490523568c1a3c68e23

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
